spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: livestock

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: agro-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.livestock.domain.event"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080